version: '2'
services:
  apachephp:
    build: docker/apache-php7-dev
    container_name: superleansilexplate-dev
    ports:
      - 8088:80
    links:
      - typo3-db:db
    volumes:
      - ./:/var/www/app
      - ./upload:/var/www/upload
      - ./public_html:/var/www/html
      - ./fonts:/usr/share/fonts
    restart: 'no' #always
  typo3-db:
    build: ./docker/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=typoalphaport
      - MYSQL_USER=typoalphaport
      - MYSQL_PASSWORD=9bsGhtpHy[SFZ?eAZxdc
      - MYSQL_DATABASE=typoalphaport
    ports:
      - '3306:3306'
    restart: 'no' #always
    volumes_from:
      - DatabaseData
  DatabaseData:
    image: mysql:5.6.25
    entrypoint: /bin/bash
