version: '2'
services:
  apachephp:
    build: docker/apache-php7-dev
    container_name: property_manager-dev
    ports:
      - 8088:80
    links:
      - mysql:db
    volumes:
      - ./:/var/www
    volumes_from:
        - Data
    restart: 'no' #always
  mysql:
    build: ./docker/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=property_manager
      - MYSQL_USER=property_manager
      - MYSQL_PASSWORD=property_manager
      - MYSQL_DATABASE=property_manager
    ports:
      - '3306:3306'
    restart: 'no' #always
    volumes_from:
      - DatabaseData
  DatabaseData:
    image: mysql:5.6.25
    entrypoint: /bin/bash
  Data:
    image: busybox
    volumes:
      - /var/www/var/cache
      - /var/www/var/logs
      - /var/www/var/sessions

