<?php

namespace AppBundle\Repository;

/**
 * AddressTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
