<?php

namespace AppBundle\Repository;

/**
 * ApartmentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApartmentTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
