<?php

namespace AppBundle\Repository;

/**
 * CostTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CostTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
