<?php

namespace AppBundle\Repository;

/**
 * LettingSidecostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LettingSidecostRepository extends \Doctrine\ORM\EntityRepository
{
}
