<?php

namespace AppBundle\Repository;

/**
 * LettingsidecostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LettingsidecostRepository extends \Doctrine\ORM\EntityRepository
{
}
