<?php

namespace AppBundle\Repository;

/**
 * LettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LettingRepository extends \Doctrine\ORM\EntityRepository
{
}
