<?php

namespace AppBundle\Repository;

/**
 * MeterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeterRepository extends \Doctrine\ORM\EntityRepository
{
}
