<?php

namespace AppBundle\Repository;

/**
 * MeterreadingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeterreadingRepository extends \Doctrine\ORM\EntityRepository
{
}
