<?php

namespace AppBundle\Repository;

/**
 * MeterTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeterTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
