<?php

namespace AppBundle\Repository;

/**
 * PersonAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonAddressRepository extends \Doctrine\ORM\EntityRepository
{
}
