<?php

namespace AppBundle\Repository;

/**
 * TenantAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TenantAddressRepository extends \Doctrine\ORM\EntityRepository
{
}
