# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  #service_name:
  #    class: AppBundle\Directory\ClassName
  #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
  admin.users:
      class: AppBundle\Admin\UserAdmin
      arguments: [~, AppBundle\Entity\User, ~]
      tags:
        - { name: sonata.admin, manager_type: orm, label: Users }
  admin.buildings:
      class: AppBundle\Admin\BuildingAdmin
      arguments: [~, AppBundle\Entity\Building, ~]
      tags:
        - { name: sonata.admin, manager_type: orm, label: Buildings }
  admin.apartments:
      class: AppBundle\Admin\ApartmentAdmin
      arguments: [~, AppBundle\Entity\Apartment, ~]
      tags:
        - { name: sonata.admin, manager_type: orm, label: Apartments }
  admin.apartment_types:
      class: AppBundle\Admin\ApartmentTypeAdmin
      arguments: [~, AppBundle\Entity\ApartmentType, ~]
      tags:
        - { name: sonata.admin, manager_type: orm, label: Apartments Types}
  admin.address:
      class: AppBundle\Admin\AddressAdmin
      arguments: [~, AppBundle\Entity\Address, ~]
      tags:
        - { name: sonata.admin, manager_type: orm, label: Addresses }
  admin.address_types:
        class: AppBundle\Admin\AddressTypeAdmin
        arguments: [~, AppBundle\Entity\AddressType, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Address Types}
  admin.people:
    class: AppBundle\Admin\PersonAdmin
    arguments: [~, AppBundle\Entity\Person, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: People }
  admin.tenant:
    class: AppBundle\Admin\TenantAdmin
    arguments: [~, AppBundle\Entity\Tenant, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Tenants }
  admin.tenant_addresses:
    class: AppBundle\Admin\TenantAddressAdmin
    arguments: [~, AppBundle\Entity\TenantAddress, ~]
    tags:
        - { name: sonata.admin, manager_type: orm, label: Tenant Addresses }

