# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  #service_name:
  #    class: AppBundle\Directory\ClassName
  #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

  # Properties
  admin.address:
      class: AppBundle\Admin\AddressAdmin
      arguments: [~, AppBundle\Entity\Address, ~]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Properties, label: Addresses }
  admin.buildings:
      class: AppBundle\Admin\BuildingAdmin
      arguments: [~, AppBundle\Entity\Building, ~]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Properties, label: Buildings }
      calls:
        - [addChild, ['@admin.apartments']]
  admin.apartments:
      class: AppBundle\Admin\ApartmentAdmin
      arguments: [~, AppBundle\Entity\Apartment, ~]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Properties, label: Apartments }
  admin.lettings:
      class: AppBundle\Admin\LettingAdmin
      arguments: [~, AppBundle\Entity\Letting, ~]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Properties, label: Lettings }
      calls:
        - [addChild, ['@admin.letting_sidecosts']]
  admin.letting_sidecosts:
      class: AppBundle\Admin\LettingsidecostAdmin
      arguments: [~, AppBundle\Entity\Lettingsidecost, ~]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Properties, label: Letting Sidecosts}
  admin.meters:
      class: AppBundle\Admin\MeterAdmin
      arguments: [~, AppBundle\Entity\Meter, ~]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Properties, label: Meters }
      calls:
        - [addChild, ['@admin.meter_readings']]
  admin.meter_readings:
      class: AppBundle\Admin\MeterreadingAdmin
      arguments: [~, AppBundle\Entity\Meterreading, ~]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Properties, label: Meter Readings }

  #Basic Data
  admin.people:
    class: AppBundle\Admin\PersonAdmin
    arguments: [~, AppBundle\Entity\Person, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: Basic Data, label: People }
    calls:
      - [addChild, ['@admin.person_addresses']]
  admin.users:
      class: AppBundle\Admin\UserAdmin
      arguments: [~, AppBundle\Entity\User, ~]
      tags:
        - { name: sonata.admin, manager_type: orm, group: Basic Data, label: Users }
  admin.person_addresses:
          class: AppBundle\Admin\PersonAddressAdmin
          arguments: [~, AppBundle\Entity\PersonAddress, ~]
          tags:
            - { name: sonata.admin, manager_type: orm, group: Basic Data, label: People Addresses }

  #System
  admin.apartment_types:
      class: AppBundle\Admin\ApartmentTypeAdmin
      arguments: [~, AppBundle\Entity\ApartmentType, ~]
      tags:
        - { name: sonata.admin, manager_type: orm, group: System, label: Apartments Types}
  admin.address_types:
        class: AppBundle\Admin\AddressTypeAdmin
        arguments: [~, AppBundle\Entity\AddressType, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, group: System, label: Address Types}
  admin.meter_types:
        class: AppBundle\Admin\MeterTypeAdmin
        arguments: [~, AppBundle\Entity\MeterType, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, group: System, label: Meter Types}
  admin.cost_types:
        class: AppBundle\Admin\CostTypeAdmin
        arguments: [~, AppBundle\Entity\CostType, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, group: System, label: Cost Types}
  admin.units:
        class: AppBundle\Admin\UnitAdmin
        arguments: [~, AppBundle\Entity\Unit, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, group: System, label: Units}
  admin.currencies:
        class: AppBundle\Admin\CurrencyAdmin
        arguments: [~, AppBundle\Entity\Currency, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, group: System, label: Currencies}

