# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  #service_name:
  #    class: AppBundle\Directory\ClassName
  #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
  admin.address:
      class: AppBundle\Admin\AddressAdmin
      arguments: [~, AppBundle\Entity\Address, ~]
      tags:
        - { name: sonata.admin, manager_type: orm, label: Addresses }
  admin.address_types:
        class: AppBundle\Admin\AddressTypeAdmin
        arguments: [~, AppBundle\Entity\AddressType, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Address Types}
  admin.tenant:
    class: AppBundle\Admin\TenantAdmin
    arguments: [~, AppBundle\Entity\Tenant, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Tenants }
  admin.tenant_addresses:
    class: AppBundle\Admin\TenantAddressAdmin
    arguments: [~, AppBundle\Entity\TenantAddress, ~]
    tags:
        - { name: sonata.admin, manager_type: orm, label: Tenant Addresses }

